### PR TITLE
Fixes #11335: Default manager for ObjectChange should filter by installed apps

### LINKED ISSUE #11335: bae.html throws an 'NoneType' object has no attribute '_base_manager' when a plugin is disabled
### NetBox version

v3.3.10

### Python version

3.8

### Steps to Reproduce

1. install/enable a plugin
2. perform some actions, so that the changelog contains log entries related to that plugin in the top 10
3. disable the plugin (remove it from PLUGINS
4. restart netbox
5. open the homepage

### Expected Behavior

Homepage is shown

### Observed Behavior

An error is thrown referencing the changelog object of the disabled plugin

```
Traceback (most recent call last):
  File "/opt/netbox/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/netbox/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/netbox/venv/lib/python3.9/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/netbox/venv/lib/python3.9/site-packages/django/views/generic/base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "/opt/netbox/netbox/netbox/views/misc.py", line 130, in get
    return render(request, self.template_name, {
  File "/opt/netbox/venv/lib/python3.9/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/opt/netbox/venv/lib/python3.9/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/opt/netbox/venv/lib/python3.9/site-packages/django/template/backends/django.py", line 62, in render
    return self.template.render(context)
  File "/opt/netbox/venv/lib/python3.9/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/opt/netbox/venv/lib/python3.9/site-packages/django/test/utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
  File "/opt/netbox/venv/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/opt/netbox/venv/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/opt/netbox/venv/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/opt/netbox/venv/lib/python3.9/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/opt/netbox/venv/lib/python3.9/site-packages/django/test/utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
  File "/opt/netbox/venv/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/opt/netbox/venv/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/opt/netbox/venv/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/opt/netbox/venv/lib/python3.9/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/opt/netbox/venv/lib/python3.9/site-packages/django/test/utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
  File "/opt/netbox/venv/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/opt/netbox/venv/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/opt/netbox/venv/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/opt/netbox/venv/lib/python3.9/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/opt/netbox/venv/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/opt/netbox/venv/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/opt/netbox/venv/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/opt/netbox/venv/lib/python3.9/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/opt/netbox/venv/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/opt/netbox/venv/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/opt/netbox/venv/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/opt/netbox/venv/lib/python3.9/site-packages/django/template/defaulttags.py", line 322, in render
    return nodelist.render(context)
  File "/opt/netbox/venv/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/opt/netbox/venv/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/opt/netbox/venv/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/opt/netbox/venv/lib/python3.9/site-packages/django_tables2/templatetags/django_tables2.py", line 167, in render
    return template.render(context={"table": table}, request=request)
  File "/opt/netbox/venv/lib/python3.9/site-packages/django/template/backends/django.py", line 62, in render
    return self.template.render(context)
  File "/opt/netbox/venv/lib/python3.9/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/opt/netbox/venv/lib/python3.9/site-packages/django/test/utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
  File "/opt/netbox/venv/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/opt/netbox/venv/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/opt/netbox/venv/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/opt/netbox/venv/lib/python3.9/site-packages/django/template/defaulttags.py", line 321, in render
    if match:
  File "/opt/netbox/venv/lib/python3.9/site-packages/django_tables2/rows.py", line 325, in __len__
    length = len(self.data)
  File "/opt/netbox/venv/lib/python3.9/site-packages/django_tables2/data.py", line 156, in __len__
    self._length = len(self.data)
  File "/opt/netbox/venv/lib/python3.9/site-packages/django/db/models/query.py", line 376, in __len__
    self._fetch_all()
  File "/opt/netbox/venv/lib/python3.9/site-packages/django/db/models/query.py", line 1869, in _fetch_all
    self._prefetch_related_objects()
  File "/opt/netbox/venv/lib/python3.9/site-packages/django/db/models/query.py", line 1258, in _prefetch_related_objects
    prefetch_related_objects(self._result_cache, *self._prefetch_related_lookups)
  File "/opt/netbox/venv/lib/python3.9/site-packages/django/db/models/query.py", line 2298, in prefetch_related_objects
    obj_list, additional_lookups = prefetch_one_level(
  File "/opt/netbox/venv/lib/python3.9/site-packages/django/db/models/query.py", line 2440, in prefetch_one_level
    ) = prefetcher.get_prefetch_queryset(instances, lookup.get_current_queryset(level))
  File "/opt/netbox/venv/lib/python3.9/site-packages/django/contrib/contenttypes/fields.py", line 199, in get_prefetch_queryset
    ret_val.extend(ct.get_all_objects_for_this_type(pk__in=fkeys))
  File "/opt/netbox/venv/lib/python3.9/site-packages/django/contrib/contenttypes/models.py", line 185, in get_all_objects_for_this_type
    return self.model_class()._base_manager.using(self._state.db).filter(**kwargs)
AttributeError: 'NoneType' object has no attribute '_base_manager'
```

I ran again this, when I had to disable a plugin after upgrading to v3.4, as the plugin was not yet compatible.
It would be great if the changelog is not that sensitive to disabled/removed plugins. I see this issue surfaces regularly and on different places where the changelog is shown

### PR DESCRIPTION
**Pull request by jeremystretch**
### Fixes: #11335

Introduce a custom default manager for ObjectChange, which automatically filters results to those referencing models belonging to currently installed apps.

All credit goes to @kkthxbye-code for coming up with this solution!

### CODE REVIEW

File: netbox/extras/querysets.py [hunk 1]
```diff
@@ -151,3 +152,14 @@ def _get_config_context_filters(self):
...
+
+
+class ObjectChangeManager(Manager.from_queryset(RestrictedQuerySet)):
+
+    def get_queryset(self):
+        # Exclude any change records which refer to an instance of a model that's no longer installed. This
+        # can happen when a plugin is removed but its data remains in the database, for example.
+        app_labels = [
+            app.split('.')[-1] for app in settings.INSTALLED_APPS
+        ]
```
Comment (kkthxbye-code) [inline netbox/extras/querysets.py:164]:
```suggestion
        app_labels = [
            app.split('.')[0] for app in settings.INSTALLED_APPS
        ]
```

I think this is supposed to the the first element. I tested with netbox-dns, and this is what INSTALLED_APPS contains:

```
>>> settings.INSTALLED_APPS
['django.contrib.admin', 'django.contrib.auth', 'django.contrib.contenttypes', 'django.contrib.sessions', 'django.contrib.messages', 'django.contrib.staticfiles', 'django.contrib.humanize', 'corsheaders', 'debug_toolbar', 'graphiql_debug_toolbar', 'django_filters', 'django_tables2', 'django_prometheus', 'graphene_django', 'mptt', 'rest_framework', 'social_django', 'taggit', 'timezone_field', 'circuits', 'dcim', 'ipam', 'extras', 'tenancy', 'users', 'utilities', 'virtualization', 'wireless', 'django_rq', 'drf_yasg', 'netbox_dns.DNSConfig']
```

So the app_label for netbox_dns will be `netbox_dns` and not `DNSConfig`. I see that this is probably different for the django prefixed apps, where I'm guessing the app_label is actually the last part, but we do not generate changelogs for built-in django apps so not sure if it matters?

**Review by kkthxbye-code — CHANGES_REQUESTED** [review]

File: netbox/extras/querysets.py (hunk 1 above)
Comment (kkthxbye-code) [reply netbox/extras/querysets.py:164]: Slightly more involved solution that also works, and is probably more correct.

```
# Add to imports
from django.apps import apps
from django.contrib.contenttypes.models import ContentType

app_labels = set(
    ContentType.objects.get_for_model(model).app_label for model in apps.get_models()
)
```

Tested working with netbox_dns. Not sure if there's any exotic plugins out that that could break though.

Comment (jeremystretch) [reply netbox/extras/querysets.py:164]: Good call. Felt kinda dumb when I was writing it tbh. This is definitely cleaner.

Comment (jeremystretch) [reply netbox/extras/querysets.py]: This has the added benefit of validating specific models, rather than just valid apps.

Comment (kkthxbye-code) [reply netbox/extras/querysets.py]: Posting my slack message here as well for posterity:

> ContentType.objects.clear_cache() after app_labels = ... fixes tests for me

**Comment by kkthxbye-code** [comment]
Posting my slack message here as well for posterity:

> ContentType.objects.clear_cache() after app_labels = ... fixes tests for me

**Comment by jeremystretch** [comment]
We're probably breaking some Django rules by attempting to evaluate registered apps within the model's base manager. A compromise might be to introduce an alternate manager that returns only the "valid" instances (e.g. `ObjectChange.valid_objects.all()`, which can be called from views. This won't address the potential issue globally but it might be a sufficient band-aid to address the (somewhat niche) concern.

**Comment by jeremystretch** [comment]
Although the current approach appears to resolve the root issue, it causes the tests to fail, presumably because we're attempting to resolve the content types too early. There may be a way to resole these lazily; still need to dig into this.

**Comment by abhi1693** [comment]
@jeremystretch This is ready for another review

File: netbox/extras/querysets.py [hunk 2]
```diff
@@ -151,3 +153,14 @@ def _get_config_context_filters(self):
...
         return base_query
+
+
+class ObjectChangeQuerySet(RestrictedQuerySet):
+
+    def valid_models(self):
+        # Exclude any change records which refer to an instance of a model that's no longer installed. This
+        # can happen when a plugin is removed but its data remains in the database, for example.
+        content_type_ids = set(
+            ct.pk for ct in ContentType.objects.get_for_models(*apps.get_models()).values()
```
Comment (jeremystretch) [inline netbox/extras/querysets.py:164]: I'm still getting hung up on this approach. While it does work, it seems far from ideal, and I worry about the performance impact.

Comment (abhi1693) [reply netbox/extras/querysets.py:164]: How about using `Subquery` here? I'm not exactly sure if that's going to improve anything performance wise

Comment (abhi1693) [reply netbox/extras/querysets.py:164]: I played around in django shell with subquery and you can try something like this

```
ObjectChange.objects.filter(changed_object_type_id__in=Subquery(ContentType.objects.filter(model__in=[m._meta.model_name for m in apps.get_models()]).values_list("pk")))
```

Comment (jeremystretch) [reply netbox/extras/querysets.py:164]: It's the base query that concerns me, filtering for `id IN [1, 2, 3, ...]`. It just seems really inefficient, but I haven't been able to come up with a more clever solution.
