### ISSUE TITLE
'User' object has no attribute 'ldap_username' error when attempting to change password

### ISSUE THREAD

**Issue by NielsH** [netbox-community/netbox#3747]
### Environment
* Python version:  3.5.3
* NetBox version:  2.6.8

Hello!

I'm a new Netbox user and just installed netbox 2.6.8. Everything seems to work except 1 thing:
When I go to `/user/password/` I get the following error:
```
There was a problem with your request. Please contact an administrator.

The complete exception is provided below:

<class 'AttributeError'>

'User' object has no attribute 'ldap_username'
If further assistance is required, please post to the NetBox mailing list.
```

Does anyone know what could cause this?

Cheers!
Niels

**Comment by hSaria** [comment]
You'll want to change the bug report to conform with the provided templates, or the maintainers will close the ticket.

This is a bug introduced in https://github.com/netbox-community/netbox/commit/7f779e39426eb3c24dda9684c1b1e2859ec4fac0#diff-c2e485b15a0afbb3469a4e87756930b5R15

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using one of the templates provided [here](https://github.com/digitalocean/netbox/issues/new/choose). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss) instead.
