### ISSUE TITLE
AttributeError when creating a Custom Field Choice Set with base choices

### ISSUE THREAD

**Issue by bctiemann** [netbox-community/netbox#22325]
### NetBox Edition

NetBox Community

### NetBox Version

v4.6.1

### Python Version

3.12

### Steps to Reproduce

1. Navigate to **Customization → Custom Field Choice Sets → Add**
2. Select any built-in base choice set (e.g. IATA, ISO 3166, or UN/LOCODE)
3. Click **Create**

### Expected Behavior

The choice set is created successfully.

### Observed Behavior

An `Internal Server Error` is returned with the following traceback:

```
File "netbox/extras/models/customfields.py", line 975, in clean
    valid_choice_values.update(CHOICE_SETS.get(self.base_choices).values())
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'values'
```

`CHOICE_SETS` values (IATA, ISO_3166, UN_LOCODE) are lists of `(value, label)` tuples, not dicts. The call to `.values()` was introduced in #21984 and treats them as dicts.

**Fix:** replace the `.values()` call with an iteration that extracts the first element from each tuple:

```python
valid_choice_values.update(value for value, _ in CHOICE_SETS.get(self.base_choices))
```
