### ISSUE TITLE
AttributeError on API - 'OrderedDict' object has no attribute 'register'

### ISSUE THREAD

**Issue by sjhloco** [netbox-community/netbox#4248]
### Environment
* ESX 6.5.0 Update1 (Build 5969303)
* 1 CPU, 2048 Mem, 32 Gig hdd
* Ubuntu-18.04.2-desktop
* Netbox v2.7.7
* Python 3.7.6

### Steps to Reproduce
1. Build netbox as per attached steps (*netbox_build*)
2. Go to root API page http://192.168.10.201/api/ or any other sections API page http://192.168.10.201/api/dcim/  

I have done the build several times as per the attached steps and am able to replicate the problem each time. Once installed everything works fine and you can use pynetbox to call the APIs to create objects. It is just when trying to access the API by URL in a browser you have this issue.

*error_requirements.txt* is the requirements after the fresh build whilst the issue is happening. If I downgrade it to *djangorestframework==3.9.4* and restart *netbox.service* (*sudo systemctl restart netbox.service*) the problem goes away. See *work_requirements.txt* for what is changed after downgrading djangorestframework, it is only djangorestframework version. I can flip back and forward between the 2 versions of djangorestframework, it always works with 3.9.4 and does not work with 3.10.3.

### Expected Behavior
See API page

### Observed Behavior
![image](https://user-images.githubusercontent.com/33333983/75121587-5c788080-568d-11ea-9256-c76738c8ae51.png)
[netbox_build.txt](https://github.com/netbox-community/netbox/files/4242632/netbox_build.txt)
[error_requirements.txt](https://github.com/netbox-community/netbox/files/4242663/error_requirements.txt)
[work_requirements.txt](https://github.com/netbox-community/netbox/files/4242664/work_requirements.txt)

**Comment by hSaria** [comment]
I couldn't replicate this issue. I'm running `djangorestframework` v3.10.3.

**Comment by jeremystretch** [comment]
We have CI tests in place for these views, and given that the tests are not failing this is likely something related to your specific installation. I suggest deleting your current virtual environment and completely rebuilding it with **only** the packages from `requirements.txt`. You can compare the state of your virtual environment to a CI build [such as this one](https://travis-ci.com/netbox-community/netbox/builds/150124650) to look for any deviations. (Expand the line which reads `pip install -r requirements.txt` and look for the line beginning with "Successfully installed" to see the list of packages installed by pip for the test.)

I'm going to close this issue as it's not currently replicable, but if you discover something that you believe needs to be changed in NetBox please feel free to comment.
