### ISSUE TITLE
Device information not available

### ISSUE THREAD

**Issue by deku-m** [netbox-community/netbox#13115]
### NetBox version

v3.5.5

### Python version

3.10

### Steps to Reproduce

1. Go to devices
2. Click on a created device 
3. Error pops up

### Expected Behavior

When clicking the device you should see the device information.

### Observed Behavior

Server Error

```
<class 'AttributeError'>

'ImageDraw' object has no attribute 'text-size'

Python version: 3.10.6
Netbox version: 3.5.5
```

**Comment by abhi1693** [comment]
Thank you for opening a bug report. Unfortunately, the information you have provided is not sufficient for someone else to attempt to reproduce the reported behavior. Remember, each bug report must include detailed steps that someone else can follow on a clean, empty NetBox installation to reproduce the exact problem you're experiencing. These instructions should include the creation of any involved objects, any configuration changes, and complete accounting of the actions being taken. Also be sure that your report does not reference data on the public NetBox demo, as that is subject to change at any time by an outside party and cannot be relied upon for bug reports.

**Comment by kkthxbye-code** [comment]
ImageDraw from the PIL library is not used in netbox as far as I can tell. Seems like the most likely cause is the plugin netbox_qr. If you are using that plugin, disable it.

**Comment by deku-m** [comment]
That was the case, sorry for the mistake.

**Comment by sebim2022** [comment]
hi, since upgrading netbox to 3.5.5 we cannot use qr code plugin any more. any chance to fix this? 
Server Error
There was a problem with your request. Please contact an administrator.

The complete exception is provided below:

<class 'AttributeError'>

'ImageDraw' object has no attribute 'textsize'

Python version: 3.8.10
NetBox version: 3.5.6

kind regards, sebastian

**Comment by abhi1693** [comment]
@sebim2022 This issue is not due to core NetBox but a bug in the plugin as `textsize` is removed from Pillow in v10. You should ask the developer of the plugin to update the code instead.
