### ISSUE TITLE
ImportError: cannot import name 'Mapping' from 'collections'

### ISSUE THREAD

**Issue by cimnine** [netbox-community/netbox#3783]
### Environment
* Python version:  3.9-rc
* NetBox version:  2.7-beta1

### Steps to Reproduce

1. `./manage.py migrate`

### Expected Behavior

Netbox/Django applies the migrations.

### Observed Behavior

An error occurs:

```
Traceback (most recent call last):
  File "/opt/netbox/netbox/./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/usr/local/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.9/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/usr/local/lib/python3.9/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1016, in _gcd_import
  File "<frozen importlib._bootstrap>", line 993, in _find_and_load
  File "<frozen importlib._bootstrap>", line 977, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 786, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/netbox/netbox/circuits/models.py", line 8, in <module>
    from dcim.models import CableTermination
  File "/opt/netbox/netbox/dcim/models.py", line 18, in <module>
    from extras.models import ConfigContextModel, CustomFieldModel, ObjectChange, TaggedItem
  File "/opt/netbox/netbox/extras/models.py", line 15, in <module>
    from jinja2 import Environment
  File "/usr/local/lib/python3.9/site-packages/jinja2/__init__.py", line 33, in <module>
    from jinja2.environment import Environment, Template
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 16, in <module>
    from jinja2.defaults import BLOCK_START_STRING, \
  File "/usr/local/lib/python3.9/site-packages/jinja2/defaults.py", line 32, in <module>
    from jinja2.tests import TESTS as DEFAULT_TESTS
  File "/usr/local/lib/python3.9/site-packages/jinja2/tests.py", line 13, in <module>
    from collections import Mapping
ImportError: cannot import name 'Mapping' from 'collections' (/usr/local/lib/python3.9/collections/__init__.py)
```

### Hints

This appears to be an issue in Jinja2 and [appears to be fixed in `2.10.2`](http://jinja.palletsprojects.com/en/2.10.x/changelog/#version-2-10-2) of jinja2. (The current release of jinja2 is `2.10.3`.)

**Comment by DanSheps** [comment]
Can you try this on a non release candidate of python?

**Comment by cimnine** [comment]
Yes. All works with Python < 3.9, but this will stop working in Python 3.9. The method in quedtion is already deprecated in 3.7 and 3.8.

So there's no hurry fixing this, but eventually this work needs to be done anyway. So why procrastinate?

**Comment by jeremystretch** [comment]
Static requirements are bumped on every 2.x release; versions are pinned unless there is a specific need to upgrade (e.g. fixing a bug). This will be addressed in the upcoming v2.7 release.
