### ISSUE TITLE
netbox.events_processor ERROR: Cannot import events pipeline extras.events.process_event_queue error: 'ScriptModule' object has no attribute 'python_class'

### ISSUE THREAD

**Issue by Rukas307** [netbox-community/netbox#16326]
### Deployment Type

Self-hosted

### NetBox Version

4.0.3

### Python Version

3.11

### Steps to Reproduce

1. Create the basic requirements for a script to run and attempt to log anything from the script, such as self.log_info(data).
2. Create a data source for the script stored on the local machine
3. Connected to an event rule using event triggers update and create, I have tested Device, Device Role and IP Address in my use case as the object types.
4. Create or update a Device. 
![image](https://github.com/netbox-community/netbox/assets/124249850/59c6b14d-492d-4586-9918-a52967a04d48)

### Expected Behavior

Logging script information to the form will occur and the script will run.

### Observed Behavior
![image](https://github.com/netbox-community/netbox/assets/124249850/d2274011-8abc-4cba-9e3f-8ef9c9203a32)

netbox.events_processor ERROR: Cannot import events pipeline extras.events.process_event_queue error: 'ScriptModule' object has no attribute 'python_class'

I am able to utilise the script without logging and get an expected result.

**Comment by Rukas307** [comment]
Hi @arthanson I have updated the post, including the sample script screen shot.

**Comment by arthanson** [comment]
@Rukas307 I'm running your script and it is working fine on my system.  Can you please try re-starting your RQ queue to check if that works?

**Comment by Rukas307** [comment]
> @Rukas307 I'm running your script and it is working fine on my system. Can you please try re-starting your RQ queue to check if that works?

I have restarted RQ Queue and am still seeing the same issue.

**Comment by arthanson** [comment]
Closing as no response, @Rukas307 please open as a discussion

**Comment by PaulR282** [comment]
I have the same problem. I already opened a discussion for this: #16912 This happened when upgrading to v4 and having event rules that trigger scripts.

**Comment by jhofmueller** [comment]
This is a real issue. I just upgrade one of our instances from 3.7.8 to 4.0.9 and some events did not work any more. The procedure discussed here [#16912](https://github.com/netbox-community/netbox/discussions/16912) worked.

The thing is that events fail silently and one only finds out what is wrong when one looks at the logs after finding out that scripts/webhooks did not run.
