### ISSUE TITLE
class 'AttributeError' 'FHRPGroup' object has no attribute 'parent_object'

### ISSUE THREAD

**Issue by uRhaineWork** [netbox-community/netbox#9575]
### NetBox version

v3.2.5

### Python version

3.9

### Steps to Reproduce

I dont have any special steps, but rather I would like to inform that something like this happened:
After updating to 3.2.5 from 3.2.4, clicking any IP address object that is under vrrpv2 FHR group, i get the result:
`<class 'AttributeError'> 'FHRPGroup' object has no attribute 'parent_object'`

Newly added or old, doesnt matter. Tried changing status and role, no go.
Not sure why this happens, reverted to 3.2.4 and it works fine. After update I didnt do much, few added FHR's and IP's attached to intefaces in devices, nothing mind bogling.

### Expected Behavior

Can view IP details after clicking it.

### Observed Behavior

`<class 'AttributeError'> 'FHRPGroup' object has no attribute 'parent_object'.`

**Comment by royaljeffr** [comment]
I am the same error as well in 3.2.5

**Comment by huntabyte** [comment]
I am working on this.
