### ISSUE TITLE
Path tracing broken for front/rear ports in REST API

### ISSUE THREAD

**Issue by srfwx** [netbox-community/netbox#18991]
### Deployment Type

Self-hosted

### NetBox Version

v4.2.6

### Python Version

3.12

### Steps to Reproduce

1. Go to  https://[SERVER_URL]/api/dcim/rear-ports/
2. Select any existing port by clicking on its "url"  
3. The REST API now display the data for a single port, for example:
  https://[SERVER_URL]/api/dcim/rear-ports/70479/
4. Append "paths/" to this URL: https://[SERVER_URL]/api/dcim/rear-ports/70479/paths

### Expected Behavior

The REST API should return the CablePaths which traverse the given pass-through port.

### Observed Behavior

'AttributeError' is raised.

```
'NoneType' object has no attribute 'model'
```

This error is not observed on NetBox 4.2.5
I believe this may have been introduced by https://github.com/netbox-community/netbox/pull/18826 ?

**Comment by jnovinger** [comment]
Looking at this now. It appears to work in the `feature` branch. Not sure what might have "fixed" it.
