### ISSUE TITLE
'PowerFeed' object has no attribute 'device'

### ISSUE THREAD

**Issue by rmammadli** [netbox-community/netbox#8393]
### NetBox version

v3.0.8

### Python version

3.9

### Steps to Reproduce

On left side menu 
1. click Power
 1a. click Power Feeds

2. select certain one from the list of availables Power Feeds.
3. in Connection section of Power Feed, click button 'Connect'
4. fill in required data in section 'Side B'
5. select / leave default value of 'Status' as 'Connected' in section 'Cable' 
6. click 'Connect' button

### Expected Behavior

Connection to Power Port will be created successfully.

### Observed Behavior

The errror raised:
'PowerFeed' object has no attribute 'device'

![server-error](https://user-images.githubusercontent.com/24699861/150190781-369baf1c-b40c-44a8-a6ab-c30c574d2b58.PNG)

**Comment by rmammadli** [comment]
By the way, it was tested and works well on Netbox v3.0.7.

**Comment by jeremystretch** [comment]
Thank you for submitting this issue. Before any further work can be done, please upgrade to the most recent stable release of NetBox (currently v3.1.6) as this issue may have already been addressed. Please then update your issue to indicate whether further action is needed.

**Comment by rmammadli** [comment]
Thank you very much for your promt reply @jeremystretch!
Your suggestion to upgrade to the most recent stable version will be considired and performed accordingly.

**Comment by rodewalder** [comment]
The same error in 3.1.6 and 3.1.7

**Comment by rmammadli** [comment]
Hi,
which version of python is installed / has been used in your case for both
versions?

**Comment by rmammadli** [comment]
Just for info, if someone gets the similar error:
the error was triggered by custom plugin developed internally.
