### ISSUE TITLE
Can't edit usergroups in the admin panel after upgrading to 3.0-beta1 from 2.11.9

### ISSUE THREAD

**Issue by al3xand3rr** [netbox-community/netbox#6804]
### NetBox version

3.0-beta1

### Python version

3.8

### Steps to Reproduce

1. Log in to netbox
2. Go to Admin panel
3. Click on "Groups" link
4. Click on any group in the list

### Expected Behavior

The Change Group page should be opened

### Observed Behavior

Server Error
There was a problem with your request. Please contact an administrator.

The complete exception is provided below:

<class 'AttributeError'>

'QuerySet' object has no attribute 'nocache'

Python version: 3.8.10
NetBox version: 3.0-beta1
If further assistance is required, please post to the NetBox mailing list.

Home Page

**Comment by jeremystretch** [comment]
Fixed under #6811.
