### PR TITLE
Fixes #3909: Regression from #3898

### LINKED ISSUE #3909: Regression from #3898 on device detail
### Environment
* Python version:  3.6.8
* NetBox version:  2.6.12

### Steps to Reproduce
1. Create two devices with an interface
2. Connect the two interfaces
3. Go to device detail page

### Expected Behavior
Page loads

### Observed Behavior
Exception `'Cable' object has no attribute '_pk'`

### PR DESCRIPTION
**Pull request by hSaria**
### Fixes: #3909 

Cable `str` method is being called during the `super()` in `__init__` which is causing an exception when accessing `_pk`. It will now fallback to `self.pk` even if it's None (I didn't go with `self.pk or self._pk` as it may trigger the same issue on a new cable).

### CODE REVIEW

**Comment by hSaria** [comment]
No longer required. See #3909
