### ISSUE TITLE
AttributeError: 'Version' object has no attribute 'dict' with packaging 26.0

### ISSUE THREAD

**Issue by kylephillipsau** [netbox-community/netbox#21254]
### NetBox Edition

NetBox Community

### NetBox Version

v4.5.1

### Python Version

3.12

### Steps to Reproduce

1. Upgrade to NetBox 4.5.1 from 4.5.0 (no plugins installed)
2. Run ./upgrade.sh (which installs latest dependencies, including packaging==26.0 as a transitive dependency)
3. Restart NetBox services
4. Access NetBox in browser and the following error occurs:
```
<class 'AttributeError'>
'Version' object has no attribute `__dict__`
```

### Expected Behavior

NetBox loads normally after upgrade without errors.

### Observed Behavior

Error:  
```
<class 'AttributeError'>
'Version' object has no attribute `__dict__`
```

The packaging library version 26.0 added `__slots__` to the Version class (https://github.com/pypa/packaging/pull/1001), which removes the `__dict__`  attribute. This breaks any code that attempts to access Version().`__dict__`.

packaging is a transitive dependency installed via gunicorn, mkdocs, and/or strawberry-graphql.

The workaround I used to get it working:
```
cd /opt/netbox
source venv/bin/activate
pip install 'packaging<26.0'
sudo systemctl restart netbox netbox-rq
```

**Comment by jeremystretch** [comment]
I'm not able to reproduce this on NetBox v4.5.1 with `packaging==26.0` installed: The service restarts successfully and I have no issues navigating the UI.

@kylephillipsau are you able to provide the complete stack trace? That would help isolate the problem.

**Comment by therepairguytt** [comment]
Not sure if this helps but this is what I got as I had the same error and the fix posted above worked for me

OS: Debian 13 Trixie
Python: 3.13.5
Install: On machine "bare metal" (it is a vm on proxmox).
Upgraded from 4.4.9 --> 4.5.1

Disabled plugins before upgrade.

Only removed IP addresses, emails, passwords and URLs

```
Internal Server Error: /

AttributeError at /
'Version' object has no attribute '__dict__'

Request Method: GET
Request URL: ***URL***
Django Version: 5.2.10
Python Executable: /opt/netbox/venv/bin/python3
Python Version: 3.13.5
Python Path: ['/opt/netbox/netbox', '/opt/netbox', '/opt/netbox/venv/bin', '/usr/lib/python313.zip', '/usr/lib/python3.13', '/usr/lib/python3.13/lib-dynload', '/opt/netbox/venv/lib/python3.13/site-packages']
Server time: Thu, 22 Jan 2026 17:17:55 -0400
Installed Applications:
['django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.humanize',
 'django.forms',
 'corsheaders',
 'django_filters',
 'django_htmx',
 'django_tables2',
 'django_prometheus',
 'strawberry_django',
 'mptt',
 'rest_framework',
 'social_django',
 'sorl.thumbnail',
 'taggit',
 'timezone_field',
 'core',
 'account',
 'circuits',
 'dcim',
 'ipam',
 'extras',
 'tenancy',
 'users',
 'utilities',
 'virtualization',
 'vpn',
 'wireless',
 'django_rq',
 'drf_spectacular',
 'drf_spectacular_sidecar']
Installed Middleware:
['corsheaders.middleware.CorsMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'django_htmx.middleware.HtmxMiddleware',
 'netbox.middleware.RemoteUserMiddleware',
 'netbox.middleware.CoreMiddleware',
 'netbox.middleware.MaintenanceModeMiddleware']


Traceback (most recent call last):
  File "/opt/netbox/venv/lib/python3.13/site-packages/django_redis/client/default.py", line 500, in decode
    value = int(value)
            ^^^^^^^^^^

During handling of the above exception (invalid literal for int() with base 10: b'\x80\x04\x95\xfb\x00\x00\x00\x00\x00\x00\x00\x8c\x11packaging.version\x94\x8c\x07Version\x94\x93\x94)\x81\x94}\x94(\x8c\x08_version\x94h\x00\x8c\x08_Version\x94\x93\x94(K\x00K\x04K\x05K\x01\x87\x94N), another exception occurred:
  File "/opt/netbox/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.13/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/netbox/utilities/views.py", line 47, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.13/site-packages/django/views/generic/base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/netbox/netbox/views/misc.py", line 53, in get
    latest_release = cache.get('latest_release')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.13/site-packages/django_redis/cache.py", line 92, in get
    value = self._get(key, default, version, client)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.13/site-packages/django_redis/cache.py", line 29, in _decorator
    return method(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.13/site-packages/django_redis/cache.py", line 99, in _get
    return self.client.get(key, default=default, version=version, client=client)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.13/site-packages/django_redis/client/default.py", line 305, in get
    return self.decode(value)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.13/site-packages/django_redis/client/default.py", line 505, in decode
    value = self._serializer.loads(value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.13/site-packages/django_redis/serializers/pickle.py", line 34, in loads
    return pickle.loads(value)
           ^^^^^^^^^^^^^^^^^^^

Exception Type: AttributeError at /
Exception Value: 'Version' object has no attribute '__dict__'
Raised during: netbox.views.misc.HomeView
```

**Comment by AleksejEgorov** [comment]
I have also faced this issue. Workaround from @kylephillipsau helps me. but...
```
(venv) root@DC1-Nbx-01:/opt/netbox# cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=24.04
DISTRIB_CODENAME=noble
DISTRIB_DESCRIPTION="Ubuntu 24.04.3 LTS"
(venv) root@DC1-Nbx-01:/opt/netbox# python -V
Python 3.12.3
````

**Comment by cnz-tbh** [comment]
I had the same issue while updating 4.4.10 -> 4.5.x. The workaround from @kylephillipsau also fix it.

```bash
NAME="Red Hat Enterprise Linux"
VERSION="9.7 (Plow)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="9.7"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Red Hat Enterprise Linux 9.7 (Plow)"
```

```bash
((venv) ) [~]$ pip list | grep packaging
packaging                          25.0
```

After updating packaging to 26.0:

```bash
((venv) ) [~]$ pip list | grep packaging
packaging                          26.0
```

Following issue appear on UI:

<img width="566" height="364" alt="Image" src="https://github.com/user-attachments/assets/0fc587df-9c26-40ee-8457-47b8a002f391" />

**Comment by jeremystretch** [comment]
Thanks @therepairguytt, that is indeed helpful, as it points us to the culprit:

```
  File "/opt/netbox/netbox/netbox/views/misc.py", line 53, in get
    latest_release = cache.get('latest_release')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by pheus** [comment]
**Thanks for the detailed report + traceback!**

I was able to reproduce this locally. It seems to require two prerequisites:

1. **Release checking is enabled** (e.g. `RELEASE_CHECK_URL = "https://api.github.com/repos/netbox-community/netbox/releases"`).
2. The cache already contains a **`latest_release` value written while running with `packaging<26.0`** (it’s a pickled `packaging.version.Version` object).

Repro steps I used:

- On NetBox 4.5.0 (with `packaging<26`), enable release checking and let the daily housekeeping task populate `latest_release` in the cache.
- Upgrade to 4.5.1 and run `./upgrade.sh` (pulls `packaging>=26.0`), restart services.
- Load `/` → `cache.get("latest_release")` tries to unpickle the old cached `Version` object and raises `AttributeError: 'Version' object has no attribute '__dict__'`.

Because the housekeeping job runs only once per day, that stale cache entry can survive across the upgrade and trigger the error until the next run (or until the cache key is cleared).

**Comment by pheus** [comment]
As a quick *intermediate* workaround (until a code-level fix lands), you can force-refresh the cached `latest_release` value by running the housekeeping job manually:

```bash
(venv) python3 netbox/manage.py housekeeping
```

This re-fetches the current release metadata and overwrites the stale cached value, which should stop the `AttributeError` on / without needing to pin `packaging`

**Comment by etherwrangler** [comment]
I got the same error after upgrading and running the housekeeping job as indicated by @pheus resolved the issue.
