### ISSUE TITLE
Regression from #3898 on device detail

### ISSUE THREAD

**Issue by hSaria** [netbox-community/netbox#3909]
### Environment
* Python version:  3.6.8
* NetBox version:  2.6.12

### Steps to Reproduce
1. Create two devices with an interface
2. Connect the two interfaces
3. Go to device detail page

### Expected Behavior
Page loads

### Observed Behavior
Exception `'Cable' object has no attribute '_pk'`

**Comment by jeremystretch** [comment]
I'm not able to recreate this. I can create a new cable and view it as well as both devices normally. Is there some other step you're taking to produce this?

**Comment by hSaria** [comment]
Apologies. I think I was accidentally running it off of the test branch. Again, sorry.
