### ISSUE TITLE
after upgrade 3.4.10 to 3.5.0 changlog didnt work

### ISSUE THREAD

**Issue by Delta1977** [netbox-community/netbox#12424]
### NetBox version

v3.5.0 

### Python version

3.10

### Steps to Reproduce

Open Changelog from Menu, Changlog on Dashboard is empty

### Expected Behavior

Changelog is shown

### Observed Behavior

<class 'AttributeError'>

'NoneType' object has no attribute '_base_manager'

Python version: 3.10.6
NetBox version: 3.5.0

**Comment by kkthxbye-code** [comment]
Duplicate of https://github.com/netbox-community/netbox/issues/11335

You disabled a plugin when upgrading and the left over changelog entries are breaking it. Re-enable the plugin or delete the changelog entries.
